//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int regId { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string contactNo { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<int> trainings { get; set; }
        public Nullable<int> goals { get; set; }
        public Nullable<int> timeSlot { get; set; }
        public Nullable<int> adMedia { get; set; }
        public Nullable<int> imageId { get; set; }
        public Nullable<int> repId { get; set; }
        public Nullable<System.DateTime> registeredOn { get; set; }
        public Nullable<System.DateTime> lastChangedOn { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual AdMedia AdMedia1 { get; set; }
        public virtual ImageDetail ImageDetail { get; set; }
        public virtual RegGoal RegGoal { get; set; }
        public virtual RegTraining RegTraining { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual TimeSlot TimeSlot1 { get; set; }
        public virtual User User { get; set; }
    }
}
